version: "3.3"
services:
  spark-master:
    image: nighttardis/docker-spark:2.4.4-hadoop2.7
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - "SPARK_LOCAL_IP=spark-master"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8080"
    command: "/start-master.sh"
    networks:
      - spark-network
  spark-worker:
    image: nighttardis/docker-spark:2.4.4-hadoop2.7
    depends_on:
      - spark-master
    ports:
      - 8080
    networks:
      - spark-network
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8080"
    command: "/start-worker.sh"

networks:
  spark-network:
    driver: bridge
    ipam:
      driver: default